spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lowerCaseServiceId: 'true'
  application:
    name: gateway
server:
  port: '8082'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka