spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodapp-orders?createDatabaseIfNotExist=true
    username: root
    password: root
  application:
    name: pedidos-ms
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8081/eureka
    instance:
      instance-id=${spring.application.name}:${random.int}
  server:
    port: '0'